<a href="https://colab.research.google.com/github/SSP-29/ML_24/blob/main/Numpy_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Library**

---



***1.Creating a single dimensional and multi dimensional arrays using numpy library.***

---



In [ ]:
#Single dimensional Array
import numpy as np
n1 = np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [ ]:
#Multi dimensional Array
import numpy as np
n2 = np.array([[10,20,30,40],[40,30,20,10]])
n2


array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [ ]:
type(n1)

numpy.ndarray

# **2.Initializing the array**

***Initializing the array with zeros***

---



In [ ]:
import numpy as np
n3=np.zeros((5,5))
n3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
import numpy as np
n4 = np.zeros((2,3))
n4

array([[0., 0., 0.],
       [0., 0., 0.]])

***Initializing the NumPy array with same number***

---






In [ ]:
import numpy as np
n1 = np.full((2,2),15)
n1

array([[15, 15],
       [15, 15]])

In [ ]:
n6 = np.full((3,6),8)
n6

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

***Initializing NumPy array within a range***

---



In [ ]:
import numpy as np
n2 = np.arange(1,51)
n2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [ ]:
#skipping 10,20.....100
n3 =np.arange(1,105,10)
n3

array([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101])

***Initializing NumPy array with random numbers***

---



In [ ]:
#printing 5 random numbers from 1-100
import numpy as np
n1 = np.random.randint(1,100,5)
n1

array([52, 96, 43, 51, 66])

# **3.NumPy-Shape**

---



***Checking the shape of Numpy Arrays***

---



In [ ]:
import numpy as np
n1 = np.array([[1,2,3],[4,5,6]])


n1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
n1.shape

(2, 3)

In [ ]:
#changing the shape
n1.shape = (3,2)
n1.shape

(3, 2)

# **4.Joining NumPy Arrays**

---



In [ ]:
#Vertical Stack
n1 = np.array([10,20,30])
n2 = np.array([40,50,60])
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
#Horizontal Stack
n1 = np.array([10,20,30])
n2 = np.array([40,50,60])
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [ ]:
#Column Stack
n1 = np.array([10,20,30])
n2 = np.array([40,50,60])
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

# **5.NumPy Intersection & Difference**

---



In [ ]:
import numpy as np
n1 = np.array([10,20,30,40,50,60])
n2 = np.array([50,60,70,80,90])
np.intersect1d(n1,n2)

array([50, 60])

In [ ]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [ ]:
np.setdiff1d(n2,n1)

array([70, 80, 90])

# **6.NumPy Array Mathematics**

---



***Addition of NumPy Arrays***

---



In [ ]:
import numpy as np
n1 = np.array([10,20])
n2 = np.array([30,40])
print("Sum:",np.sum([n1,n2]))
# or u may write np.sum([n1,n2])

Sum: 100


In [ ]:
np.sum([n1,n2],axis = 0)

array([40, 60])

In [ ]:
np.sum([n1,n2],axis = 1)

array([30, 70])

# **7.Basic Mathematics**

***Basic Addition***

---



In [ ]:
import numpy as np
n1 = np.array([10,20,30,40])
n1 = n1+1
n1

array([11, 21, 31, 41])

***Basic Subtraction***

---



In [ ]:
import numpy as np
n1 = np.array([10,20,30,40])
n1 = n1-1
n1

array([ 9, 19, 29, 39])

***Basic Multiplication***

---



In [ ]:
import numpy as np
n1 = np.array([10,20,30,40])
n1 = n1*2
n1

array([20, 40, 60, 80])

***Basic Division***

In [ ]:
import numpy as np
n1 = np.array([10,20,30,40])
n1 = n1/2
n1

array([ 5., 10., 15., 20.])

# **8.NumPy Math Functions**

---



***Mean***

In [ ]:
import numpy as np
n1 = np.array([10,20,30,40,50,60,70,80])
np.mean(n1)


45.0

***Median***

In [ ]:
import numpy as np
n1 = np.array([11,22,33,44,55,66,77,88])
np.median(n1)


49.5

***Standard Deviation***

In [ ]:
import numpy as np
n1 = np.array([10,20,30,40,50,60,70,80])
np.std(n1)


22.9128784747792

# **9.Saving and loading of NumPy Array**

---



In [ ]:
#Saving the Numpy Array
import numpy as np
n1 = np.array([10,20,30,40])
np.save('my_numpy',n1)
#loading Numpy Array
n2 = np.load('my_numpy.npy')
n2

array([10, 20, 30, 40])